returned the missing files
KEMDAK/IEEEGUCSB-System_Andriod pull request #11
Opened 2017-02-04 21:45 UTC by memmas

2017-02-06 11:03 UTC, KEMDAK requested changes

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +    AutoCompleteTextView email ;
change it to EditText

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +            public void onClick(View view) {
move the code of this method to an external method that is called `attemptLogin();` and call it here

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                            Log.i("2","it is clicked");
remove the testing logs all of them

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                                    JSONObject USer = body.getJSONObject("user") ;
rename the variable according to the conventions

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                                    String TYPE = USer.getString("type") ;
rename the variable according to the conventions

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                                        User user = new User(id,type,FN,LN,GENDER,email,BD ,IEEE_membership_ID,committeeID,committeeName,PN,settings) ;
take the last four lines common in the then and the else part

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                        else{
this else will never be executed trace your code

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public static void ForgetPassword(String email, final HTTPResponse HTTPR) {
add documentation to your method look at @rehamayman96 code.
Follow the naming conventions of variables

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                    e.printStackTrace();
call `HTTPResponse.onFailure()` if the parsing failed

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                }
add `response.close()` at the end of the `onResponse`

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                e.printStackTrace();
call `HTTPResponse.onFailure()`. and add `call.cancel()`

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public static void login(String email , String password ,final HTTPResponse HTTP_RESPONSE){
add documentation to your code and follow the naming conventions of variables

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +            e.printStackTrace();
you have to call `HTTPResponse.onFailure()` when your method fails.
Also you can't continue execution when the json object that you are trying to send is failed to be constructed

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                e.printStackTrace();
call `HTTPResponse.onFailure()`. and add `call.cancel()`

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                    HTTP_RESPONSE.onFailure(response.code(),null);}}});}
indent your code...!!
and send the failure code 500.
And add the `response.close()` at the end of `onResponse`

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/res/values/strings.xml
> +    <string name ="error_401">your email or password is wrong </string>
all the strings bellow are redundant

2017-02-06 11:03 UTC, KEMDAK commented on app/src/main/res/values/strings.xml
> +    <string name ="error_401">your email or password is wrong </string>
and they don't belong to this section of the file

2017-02-06 19:33 UTC, memmas commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +                        else{
it is working i tried it on the app

2017-02-08 10:59 UTC, KEMDAK approved these changes

2017-02-08 11:00 UTC, merged