Andrew
KEMDAK/IEEEGUCSB-System_Andriod pull request #18
Opened 2017-02-23 09:45 UTC by TheDreamHunter

2017-02-23 13:43 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +import java.io.Console;
why is this import here

2017-02-24 11:43 UTC, TheDreamHunter commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/LoginActivity.java
> +import java.io.Console;
by mistake i think....hshelo (y)

2017-02-24 12:49 UTC, KEMDAK requested changes

2017-02-24 12:49 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/fragments/user/UserUpdate.java
> +    public void updateProfile() {
document your method

2017-02-24 12:49 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +import static org.ieeeguc.ieeeguc.controllers.MainActivity.token;
weird import

2017-02-24 12:49 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +import android.widget.TextView;
weird import

2017-02-24 12:49 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public static void getCommittee(String id,final HTTPResponse HTTP_RESPONSE){
remove the `getCommittee` function from here

2017-02-24 12:49 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +            HTTP_RESPONSE.onFailure(-1,null);
change the status code to `500`

2017-02-24 12:49 UTC, KEMDAK commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
revise this file

2017-02-24 12:49 UTC, KEMDAK commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
revise this file

2017-02-24 20:41 UTC, KEMDAK requested changes
well done. keep it up :D

2017-02-24 20:41 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/MainActivity.java
> +/*
remove the testing

2017-02-24 20:41 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/fragments/user/UserUpdate.java
> +                            MainActivity.createSnackBar(body.getString("message"));
the handling of the 400 request is not like this!!

**The message is for you as a developer not for the end user**

you will find in the body and array called `error` it contains the validation errors each one with the field and its problem.

**Leave it for now we will talk about it in the retrospective meeting**

2017-02-24 20:49 UTC, KEMDAK approved these changes

2017-02-24 20:49 UTC, merged