edit committee method
KEMDAK/IEEEGUCSB-System_Andriod pull request #19
Opened 2017-02-24 12:30 UTC by SallyHabib

2017-02-24 13:17 UTC, KEMDAK requested changes

2017-02-24 13:17 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +    public void edit(int id , String token , String name , String description , final HTTPResponse HTTP_RESPONSE){
document your method & why is there an id!!!

2017-02-24 13:17 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +            public void onResponse(Call call, okhttp3.Response response) throws IOException {
remove the throwing of the `IOException`

2017-02-24 13:17 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +                }catch (JSONException e){
catch `Exceprion` instead of `JSONException`

2017-02-24 13:17 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +            HTTP_RESPONSE.onFailure(-1,null);
if the error is in the building of the body then the error is not in the connection thus the status code is not -1
However, the status code should be 500 as it is a problem from the application itself

2017-02-24 13:48 UTC, SallyHabib commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +    public void edit(int id , String token , String name , String description , final HTTPResponse HTTP_RESPONSE){
How do you want the method without Id ? 
The method have ID in its header 
api/committee/{id} put

2017-03-20 23:09 UTC, KEMDAK requested changes

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +import static org.ieeeguc.ieeeguc.models.User.CONTENT_TYPE;
remove the import as it is unused and most probably causing a syntax error

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> + * Created by abdelrahmen on 16/02/17.
remove this comment

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +    public void delete(String accessToken, final HTTPResponse HTTP_RESPONSE){
add documentation to the method

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +                    HTTP_RESPONSE.onFailure(-1,null);
fix the UI thread issue.

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +                        HTTP_RESPONSE.onFailure(500,null);
fix the UI thread issue.

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +                            HTTP_RESPONSE.onFailure(response_code,json);
fix the UI thread issue.

2017-03-20 23:09 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +                            HTTP_RESPONSE.onSuccess(response_code,json);
fix the UI thread issue.

2017-03-24 10:40 UTC, KEMDAK requested changes
**Please test your code**

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +
remove these extra lines!!

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +    HTTP_RESPONSE.onFailure(500, null);
i think you forgot this line!

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +    }
please auto indent the file.

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +import android.media.session.MediaSession;
is this a used import!

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +            Request request=new Request.Builder()
are you sure that this is a delete request?!!!

2017-03-24 10:40 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Meeting.java
> +                    HTTP_RESPONSE.onFailure(500, null);
el copy paste haywady fe dayhya sada2eeny 👎

2017-03-24 12:01 UTC, SallyHabib commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Committee.java
> +    HTTP_RESPONSE.onFailure(500, null);
ana m3mltsh edit l edit committee 5als

2017-03-25 11:19 UTC, KEMDAK approved these changes

2017-03-25 11:19 UTC, merged