Attributes of User class
KEMDAK/IEEEGUCSB-System_Andriod pull request #3
Opened 2017-01-29 22:21 UTC by SallyHabib

2017-01-30 11:51 UTC, KEMDAK requested changes
Sorry a lot of the changes i didn't tell you about it before. :(

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
>  public class User {
Add The attribute id of type int

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    private Enum type;
Create a separate file for the Enum Type and use its datatype here

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    private Enum gender;
Create a separate file for the Enum Gender and use its datatype here

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
add a : 
private JSONObject settings;

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    private Date birthdate;
add a:
private String phoneNumber;

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public User(Enum type, String firstName, String lastName, String email, Enum gender, Date birthdate, String ieeeMembershipID,
change the constructor according to the added attributes

2017-01-30 11:51 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public String getFirstName() {
remove all the setters as the attributes will be changed within this class only.
add the getters for the newly added attributes

2017-01-31 17:30 UTC, KEMDAK requested changes
There is a file named Sally delete it. and make the requested changes then push again

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/Gender.java
> +    Male,Female;
Capitalize all the letters (Java convention for Enums)

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/type.java
> +public enum type {
change the enum name to (Type)

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/type.java
> +    Member , admin , systemAdmin;
Capitalize all letters and for the please read the documentation carefully for the account types

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    private  type Type;
The type should start with capital however the variable name starts with a small letter

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    private  String LastName;
change the name of the variable to (lastName)

2017-01-31 17:30 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public User( type Type, String firstName, String lastName, String email, Gender gender, Date birthdate, String ieeeMembershipID,
add all the attributes to the cunstructor

2017-01-31 17:47 UTC, SallyHabib commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public User( type Type, String firstName, String lastName, String email, Gender gender, Date birthdate, String ieeeMembershipID,
All the attributes? In the previous comment u specify some attributes

2017-02-02 17:14 UTC, KEMDAK approved these changes

2017-02-02 17:14 UTC, merged