Abdelrahmen
KEMDAK/IEEEGUCSB-System_Andriod pull request #7
Opened 2017-02-02 22:57 UTC by darkCrakin

2017-02-03 12:27 UTC, KEMDAK requested changes
Thanks @darkCrakin and @rehamayman96 both of you did a great job on your first sprint i hope you learned something new. Keep it up 👍 

@rehamayman96 your code is clean and well structured. good job.

@darkCrakin try to be systematic in your spacing :D

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/AndroidManifest.xml
>          <activity
make the Login activity the luncher activity

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/controllers/MainActivity.java
> +    private void logout() {
add the method documentation

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +    public User(){}
remove the empty constructor

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
add `call.close();`

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
add `response.close();`

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                    call.cancel();
add `httpResponse.onFailure(-1, null);`

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +                    }
add `response.close();`

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/res/values/strings.xml
> +    <string name="failed_logout_server_error">Sorry something went wrong with the server,please try again later!</string>
change its name to "error_server_down"

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/res/values/strings.xml
>      <string name="error_incorrect_password">This password is incorrect</string>
remove the incorrect password, and add a new string that indicates incorrect credentials

2017-02-03 12:27 UTC, KEMDAK commented on app/src/main/res/values/strings.xml
> +    <string name="failed_logout_internet_problem">Failed to logout, please check your internet Connection!</string>
change its name to "error_connection"

2017-02-03 14:44 UTC, darkCrakin commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
what does it do ?

2017-02-03 15:08 UTC, darkCrakin commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
I added call.cancel() until you clarify.

2017-02-03 17:39 UTC, KEMDAK commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
Tammam

2017-02-03 17:41 UTC, darkCrakin commented on app/src/main/java/org/ieeeguc/ieeeguc/models/User.java
> +
el mafrood el branch keda gahez wi kol el changes were applied

2017-02-04 16:31 UTC, KEMDAK approved these changes

2017-02-04 16:31 UTC, merged